### ISSUE TITLE
Security vulnerability in docker compose

### ISSUE THREAD

**Issue by aaraney** [CUAHSI/nwm_subsetting#38]
@Castronova, it looks like 73328c50d62a43b688ed9f2078d2b41f84441864 and 57f7baaa50ee41103d173e2aa8661efe4a42f9dc introduced security vulnerabilities with the inclusion of oauth configuration data. We probably should prune these commits from the tree (this will be a pain) or at the least, they should be removed and new oauth configuration secrets be generated. 

In the future, we should use a docker `.env` file that is never added to this repo that contains this and any other sensitive data. See the [compose docs](https://docs.docker.com/compose/environment-variables/) for examples. Likewise, I see that the ssl certs are being accessed from a volume mount, we probably should move these to `docker-compose` secrets that are treated with more care and are always read only. See the [compose docs](https://docs.docker.com/compose/compose-file/compose-file-v3/#secrets) on this subject for an example (I also included one below).

```yaml
version: "3.9"
services:
  redis:
    image: redis:latest
    environment: 
      SSL_CERT: /run/secrets/ssl_cert
    secrets:
      - ssl_cert
secrets:
  ssl_cert:
    file: "${SSL_CERT}"
```
